using System.Collections;

using System.Collections.Generic;

using UnityEngine;

public class timer : MonoBehaviour

{

    public float timeRemaining = 2;

    public bool timerIsRunning = false;

    private void Start()

    {

        // Starts the timer automatically

        timerIsRunning = true;

    }

    void Update()

    {

        if (timerIsRunning)

        {

            if (timeRemaining > 0)

            {

                timeRemaining -= Time.deltaTime;

            }

            else

            {

                Debug.Log("Time has run out!");

                timeRemaining = 0;

                timerIsRunning = false;

            }

        }

    }

}